restaurant_corner:
    resource: "@RestaurantCornerBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@RestaurantCornerBundle/Controller/'
    type: annotation

#app:
#    resource: '@AppBundle/Controller/'
#    type: annotation
