# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
             RestaurantCornerBundle\Entity\Users: bcrypt
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~
        db_provider:
            entity:
              class: RestaurantCornerBundle:Users
              property: email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            guard:
                authenticators:
                    - RestaurantCornerBundle.form_login_authenticator
#            form_login:
#                    login_path: login
#                    check_path: login
            logout:
                    path: /logout
                    target: /
    access_control:
         - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#                - { path: ^/, roles: ROLE_ADMIN }

